---
- name: Prepare
  hosts: all

  tasks:
  - name: Ensure requirements are installed.
    apt:
      name:
        - python-pip
        - python-setuptools
        - python3-pip
        - python3-setuptools
      state: present
    become: true

  - name: Create user mary.
    user:
      name: mary
      state: present
    become: true
